### ISSUE TITLE
Closure in async lambda throw InvalidOperationException

### ISSUE THREAD

**Issue by Cooke** [dotnet/dotNext#127]
The following snippet throws `InvalidOperationException` with message `Cannot close over byref parameter '' referenced in lambda ''`

```c#
        var lambda = CodeGenerator.AsyncLambda<Func<Task<string>>>(_ =>
        {
            var hello = CodeGenerator.DeclareVariable<string>("hello");
            var foo = CodeGenerator.DeclareVariable<Func<string>>("foo");
            CodeGenerator.Statement(Expression.Assign(hello, Expression.Constant("hello")));
            CodeGenerator.Statement(Expression.Assign(foo, Expression.Lambda<Func<string>>(hello)));
            CodeGenerator.Return(Expression.Invoke(foo));
        });

        var compiled = lambda.Compile();
```

I want to use the AsyncLambda to generate async code from my own DSL but I havn't been able to work around the above issue yet.

**Comment by sakno** [comment]
Hi @Cooke , thanks for information. At the moment, closures inside of async lambdas are not supported. It's hard to implement this feature because it requires full transformation of inner lambda body and Expression Trees have no information about closure of `ParameterExpression`.

**Comment by Cooke** [comment]
Thanks for looking into it. Can it be done without changes to Linq Expressions? 

I will want to continue my DSL anyhow and need to decide if I should implement it myself (maybe a PR) or switch to transpile to C# then use Roslyn. Any hints on a path forward are appreciated.

**Comment by sakno** [comment]
I'm working on this change (it is actually committed). However, inner async lambdas will never by supported (at least from my side).

**Comment by sakno** [comment]
So, the fix is ready. @Cooke , could you please check it from `develop` branch? And don't forget what I mentioned in my comment above.

**Comment by Cooke** [comment]
Cool thanks. Looks good. I have tested a basic async lambda inside another async lambda and it seems to work, maybe it will become an issue with more complex expressions are involved?

**Comment by sakno** [comment]
It works only if you don't have closures.

**Comment by sakno** [comment]
@Cooke , can you confirm that everything is working as expected? If so, I'll publish the package.

**Comment by Cooke** [comment]
@sakno it works as expected. Thank you.

**Comment by sakno** [comment]
A new package has been published: https://www.nuget.org/packages/DotNext.Metaprogramming/4.7.5
