### ISSUE TITLE
Document recommended pattern for cluster members configuration

### ISSUE THREAD

**Issue by davhdavh** [dotnet/dotNext#146]
https://dotnet.github.io/dotNext/features/cluster/raft.html#network-transport mentions how it _can_ be done for tcp/udp, but there doesn't seem to be anywhere it is documented what the recommended pattern is for aspnetcore.
Only place I can find specifically says it is not recommended to do in production https://github.com/dotnet/dotNext/blob/master/src/examples/RaftNode/Startup.cs#L63

**Comment by sakno** [comment]
In case of ASP.NET Core, all capabilities available through DI. If you want to add/remove members dynamically, use API provided by [IRaftHttpCluster](https://dotnet.github.io/dotNext/api/DotNext.Net.Cluster.Consensus.Raft.Http.IRaftHttpCluster.html) interface. It exposes the same pair of `AddMemberAsync`/`RemoveMemberAsync` methods.
