### ISSUE TITLE
PhiAccrualFailureDetector throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by davhdavh** [dotnet/dotNext#151]
Was checking out `PhiAccrualFailureDetector` with
   `services.AddSingleton<Func<IRaftClusterMember, IFailureDetector>>(_ => new PhiAccrualFailureDetector { Threshold = 3D });`
and 7098 non-responsive and that worked just fine.
Left the cluster running with 7098 still down in the background while doing some other thing and ~2h later came back to see it crashed with this log on the leader 7096:

> 7096: 2023-02-15 16:08:15.788 +07:00 [ERR] 21.NET ThreadPool Worker The unexpected exception occurred
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at DotNext.Diagnostics.PhiAccrualFailureDetector.HeartbeatHistorySnapshot.Next(Timestamp ts) in /_/src/cluster/DotNext.Net.Cluster/Diagnostics/PhiAccrualFailureDetector.History.cs:line 116
>    at DotNext.Diagnostics.PhiAccrualFailureDetector.ReportHeartbeat(Timestamp ts) in /_/src/cluster/DotNext.Net.Cluster/Diagnostics/PhiAccrualFailureDetector.cs:line 126
>    at DotNext.Diagnostics.PhiAccrualFailureDetector.ReportHeartbeat() in /_/src/cluster/DotNext.Net.Cluster/Diagnostics/PhiAccrualFailureDetector.cs:line 93
>    at DotNext.Net.Cluster.Consensus.Raft.LeaderState`1.ClusterFailureDetector.ReportHeartbeat(TMember member) in /_/src/cluster/DotNext.Net.Cluster/Net/Cluster/Consensus/Raft/LeaderState.Monitoring.cs:line 31
>    at DotNext.Net.Cluster.Consensus.Raft.LeaderState`1.ProcessMemberResponse(Timestamp startTime, Task`1 response, Int64& term, Int32& quorum, Int32& commitQuorum, Int32& leaseRenewalThreshold) in /_/src/cluster/DotNext.Net.Cluster/Net/Cluster/Consensus/Raft/LeaderState.cs:line 185
> 7096: 2023-02-15 16:08:16.797 +07:00 [ERR] 21.NET ThreadPool Worker The unexpected exception occurred
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at DotNext.Diagnostics.PhiAccrualFailureDetector.HeartbeatHistorySnapshot.Next(Timestamp ts) in /_/src/cluster/DotNext.Net.Cluster/Diagnostics/PhiAccrualFailureDetector.History.cs:line 116
>    at DotNext.Diagnostics.PhiAccrualFailureDetector.ReportHeartbeat(Timestamp ts) in /_/src/cluster/DotNext.Net.Cluster/Diagnostics/PhiAccrualFailureDetector.cs:line 126
>    at DotNext.Diagnostics.PhiAccrualFailureDetector.ReportHeartbeat() in /_/src/cluster/DotNext.Net.Cluster/Diagnostics/PhiAccrualFailureDetector.cs:line 93
>    at DotNext.Net.Cluster.Consensus.Raft.LeaderState`1.ClusterFailureDetector.ReportHeartbeat(TMember member) in /_/src/cluster/DotNext.Net.Cluster/Net/Cluster/Consensus/Raft/LeaderState.Monitoring.cs:line 31
>    at DotNext.Net.Cluster.Consensus.Raft.LeaderState`1.ProcessMemberResponse(Timestamp startTime, Task`1 response, Int64& term, Int32& quorum, Int32& commitQuorum, Int32& leaseRenewalThreshold) in /_/src/cluster/DotNext.Net.Cluster/Net/Cluster/Consensus/Raft/LeaderState.cs:line 185
> 7096: 2023-02-15 16:08:17.814 +07:00 [WRN] 20.NET ThreadPool Worker Unresponsive cluster member https://raft3dockerclusterexample_7097/ detected

logs on 7097 shows nothing weird:

> 7097: 2023-02-15 16:08:13.756 +07:00 [INF] 3.NET ThreadPool Worker Request starting HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft application/octet-stream 37
> 7097: 2023-02-15 16:08:13.769 +07:00 [INF] 14.NET ThreadPool Worker Request finished HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft application/octet-stream 37 - 200 - - 12.6498ms
> 7097: 2023-02-15 16:08:14.760 +07:00 [INF] 14.NET ThreadPool Worker Request starting HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft - 0
> 7097: 2023-02-15 16:08:14.760 +07:00 [INF] 14.NET ThreadPool Worker Value before 39500. Value after 40000
> 7097: 2023-02-15 16:08:14.761 +07:00 [INF] 14.NET ThreadPool Worker Request finished HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft - 0 - 200 - - 0.8434ms
> 7097: 2023-02-15 16:08:15.777 +07:00 [INF] 14.NET ThreadPool Worker Request starting HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft - 0
> 7097: 2023-02-15 16:08:15.778 +07:00 [INF] 14.NET ThreadPool Worker Request finished HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft - 0 - 200 - - 0.5940ms
> 7097: 2023-02-15 16:08:16.791 +07:00 [INF] 13.NET ThreadPool Worker Request starting HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft - 0
> 7097: 2023-02-15 16:08:16.792 +07:00 [INF] 13.NET ThreadPool Worker Request finished HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft - 0 - 200 - - 0.4884ms
> 7097: 2023-02-15 16:08:17.809 +07:00 [INF] 13.NET ThreadPool Worker Request starting HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft - 0
> 7097: 2023-02-15 16:08:17.809 +07:00 [INF] 13.NET ThreadPool Worker Request finished HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft - 0 - 200 - - 0.4044ms
> 7097: 2023-02-15 16:08:18.756 +07:00 [INF] 3.NET ThreadPool Worker Request starting HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft application/octet-stream 113
> 7097: 2023-02-15 16:08:18.768 +07:00 [INF] 3.NET ThreadPool Worker Request finished HTTP/2 POST https://raft3dockerclusterexample_7097/cluster-consensus/raft application/octet-stream 113 - 200 - - 12.2750ms
> 7097: 2023-02-15 16:08:20.624 +07:00 [INF] 3.NET ThreadPool Worker Transition to Candidate state has started with term 1
> 7097: 2023-02-15 16:08:20.624 +07:00 [INF] 3.NET ThreadPool Worker Consensus cannot be reached
> 7097: 2023-02-15 16:08:20.625 +07:00 [INF] 3.NET ThreadPool Worker Term of local cluster member is 1. Election timeout 00:00:01.8500000
> 7097: 2023-02-15 16:08:22.475 +07:00 [INF] 14.NET ThreadPool Worker Transition to Candidate state has started with term 1
> 7097: 2023-02-15 16:08:24.325 +07:00 [INF] 3.NET ThreadPool Worker Transition to Candidate state has started with term 1
> 7097: 2023-02-15 16:08:26.174 +07:00 [INF] 14.NET ThreadPool Worker Transition to Candidate state has started with term 1
> 7097: 2023-02-15 16:08:28.026 +07:00 [INF] 21.NET ThreadPool Worker Transition to Candidate state has started with term 1
> 7097: 2023-02-15 16:08:29.875 +07:00 [INF] 21.NET ThreadPool Worker Transition to Candidate state has started with term 1
> 7097: 2023-02-15 16:08:31.725 +07:00 [INF] 21.NET ThreadPool Worker Transition to Candidate state has started with term 1

**Comment by sakno** [comment]
The problem is confirmed and easily reproducible. The fix will arrive asap.

**Comment by sakno** [comment]
@davhdavh , did you have a chance to test the fix? If everything is fine, I'm ready to publish a new release with the fix and things discussed in #148.
