### ISSUE TITLE
Suggestion: Change ITypeMap.GetIndex<TKey> Accessibility to Protected

### ISSUE THREAD

**Issue by zacharylayne** [dotnet/dotNext#161]
I'd like to implement `ITypeMap<T>` but to do so it seems I'd have to reimplement indexing since [`GetIndex<TKey>()`](https://github.com/dotnet/dotNext/blob/gh-pages/src/DotNext/Collections/Specialized/ITypeMap.cs#L27) is `private protected` . Would it be sensible to change `GetIndex` accessibility to `protected`?

**Comment by sakno** [comment]
`GetIndex` is an implementation detail, and may be changed in future. Indexing space is a sparse space, e.g. `GetIndex<string>` may return different indexes for different actual `TValue`. It is impractical to keep backward compatibility for this API. I may decide to change the behavior of this method or remove generic parameter at all.
