### ISSUE TITLE
ConcurrentCache throws NullReferenceException 

### ISSUE THREAD

**Issue by shaltielshmid** [dotnet/dotNext#162]
We are using the `ConcurrentCache` class from `DotNext.Runtime.Caching` in our project, with the `LFU` eviction policy. 

We access values using the `TryGetValue` function, and assign values using the indexing operator.

```cs
// Initialize the cache
int capacity = 10000;
var cache = new ConcurrentCache<string, string>(capacity, CacheEvictionPolicy.LFU);

// Get value
bool success = cache.TryGetValue(key, out var value);
// Set value
cache[key] = newValue;
```

We used this in our project and ran it with multiple threads running simultaneously and after some time it crashed with a `NullReferenceException`. There is no specific instance that it crashes on, every time we run it it crashes at a different point. 

Below is the full error:
```
Object reference not set to an instance of an object.
 at DotNext.Runtime.Caching.ConcurrentCache`2.DrainQueue()
 at DotNext.Runtime.Caching.ConcurrentCache`2.EnqueueAndDrain(Func`2 invoker, KeyValuePair target)
 at DotNext.Runtime.Caching.ConcurrentCache`2.TryGetValue(TKey key, IEqualityComparer`1 keyComparer, Int32 hashCode, TValue& value)
```

Any advice would be much appreciated! 

Thank you

**Comment by sakno** [comment]
Could you turn on debugging symbols or launch the app in Debug mode? This will able to see line numbers within the code.

**Comment by shaltielshmid** [comment]
Here are the full details of the exception:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=DotNext
  StackTrace:
   at DotNext.Runtime.Caching.ConcurrentCache`2.DrainQueue() in /_/src/DotNext/Runtime/Caching/ConcurrentCache.Queue.cs:line 125
```

In addition, here is minimal code that causes the exception:
```cs
          var ds = new Bogus.DataSets.PhoneNumbers();
          var cache = new ConcurrentCache<string, string>(10000, CacheEvictionPolicy.LFU);

          Enumerable.Range(0, 14).AsParallel().ForAll(_ => {
              foreach (int i in Enumerable.Range(0, 100000)) {
                  string num = ds.PhoneNumber();
                  if (cache.TryGetValue(num, out var _))
                      continue;
                  cache[num] = num;
              }
          });
```

**Comment by sakno** [comment]
Good to have some code snippet, but I still can't use it because `Bogus.DataSets.PhoneNumbers` is unknown to me. Could you fix it in the way when I can just copy-paste the code and get the error?

**Comment by shaltielshmid** [comment]
Sure, here you go:

```cs
            var cache = new ConcurrentCache<string, string>(10000, CacheEvictionPolicy.LFU);

            Enumerable.Range(0, 14).AsParallel().ForAll(_ => {
                foreach (int i in Enumerable.Range(0, 100000)) {
                    string num = Guid.NewGuid().ToString();
                    if (cache.TryGetValue(num, out var _))
                        continue;
                    cache[num] = num;
                }
            });
```

**Comment by sakno** [comment]
Preliminary analysis: the issue with internal pooling. Replacing `RentCommand` with a trivial implementation that instantiates a fresh instance every time demonstrates stable execution w/o exception.

**Comment by sakno** [comment]
Related [discussion](https://stackoverflow.com/questions/76334621/interlocked-compareexchange-doesnt-provide-correct-memory-ordering) on StackOverflow.

**Comment by sakno** [comment]
@shaltielshmid , could you check the latest patch from `develop` branch?

**Comment by shaltielshmid** [comment]
Absolutely, will test it by us tonight.

**Comment by shaltielshmid** [comment]
Works perfectly! Thank you!

**Comment by sakno** [comment]
A new version has been published.
