### ISSUE TITLE
Incorrect default value in documentation for BuiltInTransportConfiguration.ServerBacklog

### ISSUE THREAD

**Issue by freddyrios** [dotnet/dotNext#165]
Both in the xml code and in this doc page https://dotnet.github.io/dotNext/features/cluster/raft.html, it states that the default value is based on the number of cluster members.

In reality, the default is hardcoded to 10. 

Is it still a good idea to set it to the cluster count for larger clusters? Is it correct that it should only matter for scenarios where a whole cluster is being (re)started at the same time?

**Comment by sakno** [comment]
Btw, please check #166 announcement.
