### ISSUE TITLE
Documentation is incorrectly generated for methods using 'scoped' keyword in its params.

### ISSUE THREAD

**Issue by Bia10** [dotnet/dotNext#172]
It appears the doc generation fails to take 'scoped' keyword for method arguments into account, and then incorrectly splits the first param into multiple prams. This seem to appear wherever scoped is used as keyword for param.

![image](https://github.com/dotnet/dotNext/assets/2548763/7e717eda-6a39-4cf1-96e7-5852e31ecd4c)
![image](https://github.com/dotnet/dotNext/assets/2548763/37d16d9f-3917-4b12-9838-01d2d483865f)

Mby you alrdy noticed this, just curious where the problem is.

**Comment by sakno** [comment]
Yes, there are many issues with documentation rendering because of DocFX. This is not the only one.

**Comment by Bia10** [comment]
After Yufei's comment i actually went to build the doc myself and I was not able to preproduce this problem on .NET Core SDK 6.0.408 and DocFx 2.67.3

![image](https://github.com/dotnet/dotNext/assets/2548763/1013c01a-fa3f-4203-80b4-7ad5fdf88a61)

**Comment by sakno** [comment]
No, not yet. If want you can make a PR and modify `azure-pipelines.yml` accordingly.

**Comment by sakno** [comment]
Same but with GitHub Actions: https://www.jamescroft.co.uk/building-net-project-docs-with-docfx-on-github-pages/

**Comment by sakno** [comment]
A new documentation has been deployed.
