### ISSUE TITLE
TCP transport: request timeout if Frame header is fragmented

### ISSUE THREAD

**Issue by sakno** [dotnet/dotNext#186]
Raft client for TCP encounters timeout if protocol Frame header is fragmented when transmitting over the wire. This leads to incorrect adjustment of internal buffer size and stream waits for extra data which doesn't come.

**Comment by sakno** [comment]
cc @freddyrios

**Comment by freddyrios** [comment]
Can it lead to repeated timeouts for say 20 seconds? We had such repeated timeouts on a system, but it is unclear if th 20 seconds were purely due to energy efficient ethernet issues with Compute Module 4 or a mix of that + some bug.

**Comment by sakno** [comment]
Yes, it could lead to random timeouts. But it depends on the size of transmitted data, not the time.
