### ISSUE TITLE
Raft Cluster Asp.net Core Dynamically AddMemberAsync

### ISSUE THREAD

**Issue by guillaume-chervet** [dotnet/dotNext#196]
Hi,

Thank you again for this wonderful library.
I would like to autoscale a very small database on kubernetes (with access to the kubernetes API).
I'am testing to add dynamically some members.

My code is crashing, i do not know if it is possible to do that. 
The documentation seem to tell it is possibile with the HTTP implementation.

My test code : https://github.com/AxaFrance/SlimFaas/blob/b46f4675171d2a7a9618ec36744a5832e8f2c274/src/SlimData/Startup.cs#L251C17-L276C20

```c#
endpoints.MapPost("AddMember", async context =>
                {
                    var cluster = context.RequestServices.GetRequiredService< IRaftCluster>();
                    
                    try
                    {
                        var form = await context.Request.ReadFormAsync();
                        var key = string.Empty;
                        var value = string.Empty;
                        foreach (var formData in form)
                        {
                            value = formData.Value.ToString();
                            if (cluster.Members
                                    .Count(m => m.EndPoint == new UriEndPoint(new(value, UriKind.Absolute))) == 0)
                            {
                                await ((IRaftHttpCluster)cluster).AddMemberAsync(new Uri(value), context.RequestAborted);
                            }
                            break;
                        }
                        await context.Response.WriteAsync("", context.RequestAborted); 
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine("Unexpected error {0}", e);
                    }
                });
```

The code is crashing on line :
```c#
  await ((IRaftHttpCluster)cluster).AddMemberAsync(new Uri(value), context.RequestAborted);
```
![image](https://github.com/dotnet/dotNext/assets/52236059/24d56d86-624b-4e6d-a14a-43794ae3c591)

**Comment by sakno** [comment]
`AddMember` must be called for leader node only and the node must be online.

**Comment by sakno** [comment]
Exception should be clear about attempt to add member on the follower node.

**Comment by guillaume-chervet** [comment]
Thank you very much @sakno , i understand now.

So a node cannot start whithout any member.

**Comment by sakno** [comment]
A new node should be started in _Standby_ state. Then, you need to inform leader node about new node by calling `AddMemberAsync`.

**Comment by sakno** [comment]
4.14.4 release has been published with correct exception type. If you need further assistance, please create a discussion.
