### ISSUE TITLE
API Ref: Universally Broken Links (Wrong Repo Target)

### ISSUE THREAD

**Issue by zacharylayne** [dotnet/dotNext#198]
In the API reference, every **Edit this page** and **View Source** link targets a location under https://github.com/steffen-wilke/darkfx/.

**Comment by sakno** [comment]
Hmm, it's a template referenced as Dark Theme for output documentation. Seems like a bug in DocFX.

**Comment by zacharylayne** [comment]
Glad to be of help!

**Comment by sakno** [comment]
_Edit Page_ fixed as well.
