### ISSUE TITLE
Using Optional<T> with data validation attributes

### ISSUE THREAD

**Issue by Tiberriver256** [dotnet/dotNext#204]
Hello,

Is there any easy way to support making a class like this?

```cs
public class TestObject
{
    [StringLength(100)]
    public Optional<string?> Testing { get; set; }
}
```

and then expecting it to work with normal validation?

**Comment by sakno** [comment]
`StringLengthAttribute` is explicit about the type. It expects String, array, or collection type. `TypeConverter` doesn't help, the attribute doesn't use it for type conversion.
```
'System.InvalidCastException' in System.ComponentModel.Annotations.dll: 'The field of type DotNext.Optional`1[System.String] must be a string, array or ICollection type.'
```
I see no way in .NET library to override this behavior.

**Comment by sakno** [comment]
The only way is to derive `StringLengthAttribute` class and override `bool IsValid (object? value);` method. Let's call this `OptionalStringLengthAttribute`. If this approach works for you, I can prepare a few validation classes especially for `Optional<T>` data type.

**Comment by Tiberriver256** [comment]
Ah thanks man! Yeah that sounds like a good way forward.

**Comment by sakno** [comment]
Please review the commit above. `OptionalStringLengthAttribute` and `ValueRequiredAttribute` classes are introduced. Counterparts of `MinLengthAttribute` and `MaxLengthAttribute` were not introduced because it makes no sense to use `Optional<List<T>>` data types in data models.

**Comment by Tiberriver256** [comment]
Looks awesome man! Thank you!
