### ISSUE TITLE
Potential addition of an `OrderedDictionary<TKey, TValue>` type

### ISSUE THREAD

**Issue by alexrp** [dotnet/dotNext#220]
Context: https://github.com/dotnet/runtime/issues/24826 (especially the last 10 or so comments)

Do you think it would make sense for .NEXT to include @TylerBrinkley's [`OrderedDictionary<TKey, TValue>` implementation](https://github.com/dotnet/corefxlab/blob/archive/src/Microsoft.Experimental.Collections/Microsoft/Collections/Extensions/OrderedDictionary.cs) in `DotNext.Collections`? (Assuming Tyler takes no issue with this, of course.) It seems like there's high demand for this type but low appetite for prioritizing it from the .NET team, and it's only currently available in an [unmaintained, pre-release, and deprecated package](https://www.nuget.org/packages/Microsoft.Experimental.Collections).

**Comment by TylerBrinkley** [comment]
It's MIT licensed so please do with it what you will. Personally, outside of including it in the BCL I think it would probably be used more in a more collection focused library. I think more people would be able to discover its existence and would be more willing to take a dependency on it than a more general purpose library like this.

**Comment by alexrp** [comment]
> I think more people would be able to discover its existence and would be more willing to take a dependency on it than a more general purpose library like this.

The only general purpose collections library that immediately comes to mind here is [C5](https://github.com/sestoft/C5), but that seems to be unmaintained these days... :thinking:

One could also imagine a DotNext.Collections package, but at that point I might be asking too much of @sakno. :eyes:

**Comment by sakno** [comment]
On the one hand, I never tried to reach the goal to incorporate reusable data structures to .NEXT such as trees, collections, etc. From other side, the library has specialized collections such as [typed maps](https://dotnet.github.io/dotNext/api/DotNext.Collections.Specialized.ConcurrentTypeMap.html), [concurrent cache](https://dotnet.github.io/dotNext/api/DotNext.Runtime.Caching.ConcurrentCache-2.html), etc. Also, there is very similar discussion: #163. And it was rejected.

**Comment by alexrp** [comment]
If you don't think it belongs in .NEXT, that's totally fine. This was just the first possibility that came to mind while trying to think of a potential home for it.

**Comment by sakno** [comment]
Let's keep this issue open for now. I don't want to be a sole decision maker, .NEXT is an open-source project and community opinion matters.

**Comment by sakno** [comment]
Finally `OrderedDictionary` is [announced](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/libraries#ordereddictionarytkey-tvalue) in .NET 9. Closing issue.
