### ISSUE TITLE
If ColdStarted node is down, new leader is not elected

### ISSUE THREAD

**Issue by Pramodnm** [dotnet/dotNext#246]
Steps:
Start 1st node in coldstart mode (no knowledge of other members) - this will become a Leader node
Start a 2nd node which sends request to 1st node to join cluster. 1st Node executes AddMembersAsync - this works, node joins cluster. membership count=2
Start 3rd node, 4th, 5th nodes using step 2. membership count = 5
Leader is 1st Node
Kill 1st Node - expecting other nodes to take over as Leader
What I see if Leader is still shown as 1st Node (after 1st node is already offline) - no election takes place

It\s better to create a new issue.

_Originally posted by @sakno in https://github.com/dotnet/dotNext/discussions/62#discussioncomment-4290857_

**Comment by sakno** [comment]
Test `ClusterRecovery` checks exactly the same scenario and appropriate fix 390e5d1b
