### ISSUE TITLE
Did you remove "IEnumerable<T>.FirstOrNone"?

### ISSUE THREAD

**Issue by CodingMadness** [dotnet/dotNext#247]
Title.

It was very very useful and I had like 4 use cases in my tiny projects for it which was very convenient , sadly I do not find it anymore when I upgraded to "DotNext 5.7.0" :/

**Comment by sakno** [comment]
It was presented in 4.x but not in 5.x. It was removed in favor of C# 12 language features, e.g.:
```csharp
private static void M(IReadOnlyList<int> enumerable)
{
    int? value = enumerable is [var x] ? x : 0;
}
```

**Comment by CodingMadness** [comment]
I was not really aware of that feature, nearly forgot there are list patterns now lol, so the part in your method: `enumerable is [var x, ..]` does that check if their is a first valid item "var x" and then gets x  if there is, if not None is returned, but wouldnt it be sufficient to just do `enumerable is [var x]` ?

**Comment by sakno** [comment]
`enumerable is [var x]` checks whether the list has exactly one element.

`enumerable is [var x, ..]` checks whether the list has at least one element.

**Comment by sakno** [comment]
For `IAsyncEnumerable<T>`, `FirstOrNone` still exists because pattern matching expression is not applicable to async streams.

**Comment by CodingMadness** [comment]
> It was presented in 4.x but not in 5.x. It was removed in favor of C# 12 language features, e.g.:
> 
> ```cs
> private static void M(IReadOnlyList<int> enumerable)
> {
>     Optional<int> value = enumerable is [var x, ..] ? x : Optional.None<int>();
> }
> ```

problem with this tho is, it cannot be used on IEnumerables, and I do not want to expose it as a list in order to check for that, cause I am using heavily lazy evaluations which in this case would be defeated by this feature.

**Comment by sakno** [comment]
> it cannot be used on IEnumerables

That's true. There is related discussion: dotnet/csharplang#1039

**Comment by sakno** [comment]
Can you use `IReadOnlyCollection<T>` instead of `IReadOnlyList<T>`? List patterns are working with every type that has public `Count` or `Length` property.

**Comment by sakno** [comment]
If not, you can use `ElementAt` extension method which is still exist. Otherwise, we can consider `FirstOrNone` to be added back.

**Comment by CodingMadness** [comment]
Please consider it mate, its very strong and expressive and useful.

**Comment by sakno** [comment]
There is a problem with code signing step in CI pipeline. Trying to resolve it with .NET Foundation team, sorry for the delay.

**Comment by CodingMadness** [comment]
> There is a problem with code signing step in CI pipeline. Trying to resolve it with .NET Foundation team, sorry for the delay.

dont worry, there is no hurry with this, I have written an example for now myself, so all good, take your time

**Comment by sakno** [comment]
Finally published.
