### ISSUE TITLE
Suggestions about UserDataStorage.CopyTo() and UserDataStorage.Clear()

### ISSUE THREAD

**Issue by sakno** [dotnet/dotNext#248]
### Discussed in https://github.com/dotnet/dotNext/discussions/245

<div type='discussions-op-text'>

<sup>Originally posted by **ReneeGA2020** July  7, 2024</sup>
Suggestion 1:
It looks like UserDataStorage.CopyTo only works when the orgin UserDataStorage has anything stored, otherwise the target object's storage will not be changed. This probably worth to be mentioned in the document, or change its behavior to clear up all the UserData in the target object.

Alternately, provide a Method to check if the storage has any UserData.

Suggestion 2:
I think UserDataStorage.Clear() would be useful.</div>

**Comment by sakno** [comment]
> provide a Method to check if the storage has any UserData.

As well as `Clear` method, it's badly compatible with thread safety. I would prefer to fix the behavior of existing method.

**Comment by ReneeGA2020** [comment]
Just want to thank you for your quick response. I'm now using the new version and they works fine:)
