### ISSUE TITLE
Support for enumeration in TypeMap

### ISSUE THREAD

**Issue by adambajguz** [dotnet/dotNext#249]
The `TypeMap` doesn't support enumeration.

It would be nice if you could add support for `IEnumerable<KeyValuePair<Type, object>>` or `IEnumerable<object>` or `IReadOnlyDictionary<Type, object>` in `TypeMap`.

**Comment by sakno** [comment]
It has no support for enumeration because it doesn't know anything about `Type`. It's not based on `typeof(T)` operation.

**Comment by sakno** [comment]
Oh, I see that `IEnumerable<object>` is suitable for you. This is doable.

**Comment by adambajguz** [comment]
Thanks for quick addition of `IEnumerable<object>` support !!
