### ISSUE TITLE
AOT compilation of DotNext.Net.Cluster (and the RaftNode example) fails

### ISSUE THREAD

**Issue by guillermoeuillades** [dotnet/dotNext#254]
The AOT compilation of the RaftNode example does not work. After removing Kestrel and other HTTP dependencies that were blocking AOT compilation, I encountered a reflection dependency in DotNext.Reflection.TaskType.

`"C:\Users\administrator\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\8.0.11\tools\\ilc" @"obj\Release\net8.0\win-x64\native\RaftNode.ilc.rsp"
EXEC(0,0): Error : One or more errors occurred. (Code generation failed for method '[DotNext]DotNext.Reflection.TaskType..cctor()')
System.AggregateException: One or more errors occurred. (Code generation failed for method '[DotNext]DotNext.Reflection.TaskType..cctor()')
 ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[DotNext]DotNext.Reflection.TaskType..cctor()'
 ---> System.NotImplementedException: Open instance delegates
   at ILCompiler.DelegateCreationInfo.Create(TypeDesc, MethodDesc, TypeDesc, NodeFactory, Boolean) + 0x475
   at Internal.IL.ILImporter.ImportCall(ILOpcode, Int32) + 0x18ad
   at Internal.IL.ILImporter.ImportBasicBlock(ILImporter.BasicBlock) + 0x1d04
   at Internal.IL.ILImporter.ImportBasicBlocks() + 0x55
   at Internal.IL.ILImporter.Import() + 0x745
   at ILCompiler.ILScanner.CompileSingleMethod(ScannedMethodNode methodCodeNodeNeedingCode) + 0x5c
   --- End of inner exception stack trace ---`

Upon further investigation, I found the issue in
src/cluster/DotNext.Net.Cluster/Net/Cluster/Consensus/Raft/Tcp/TcpServer.cs, particularly in commit [413e0b185c07eaa84115951747e417ffed754af9](https://github.com/dotnet/dotNext/commit/413e0b185c07eaa84115951747e417ffed754af9), where TaskType was introduced.

  
`using static Reflection.TaskType;`
...

`
protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            CleanUp();
            if (!SpinWait.SpinUntil(noPendingConnectionsEvent.Task.GetIsCompletedGetter(), GracefulShutdownTimeout))
                logger.TcpGracefulShutdownFailed(GracefulShutdownTimeout);
        }
        base.Dispose(disposing);
    }
`

After removing the dependency on TaskType from TcpServer.cs, the AOT compilation worked successfully.

**Comment by sakno** [comment]
Seems like open delegates are not supported in AOT. This is not good, because ECMA-335 doesn't imply any restrictions on that.

**Comment by sakno** [comment]
Even `<IsAotCompatible>true</IsAotCompatible>` setting on the library doesn't catch that. I'll try to rewrite IL code to achieve AOT compatibility.

**Comment by sakno** [comment]
The implementation of `TaskType` has changed, could you please try `develop` branch?

**Comment by sakno** [comment]
I've added `DotNext.AotTests` project to the repo to verify AOT compatibility on every build. `TaskType` now is working normally.

**Comment by sakno** [comment]
All examples in the repo (including `RaftNode`) are rewritten with `SlimBuilder` and AOT support.
