### ISSUE TITLE
AsyncBarrier does not work

### ISSUE THREAD

**Issue by ascott18** [dotnet/dotNext#73]
I can't get `AsyncBarrier` to work at all, even under trivial usage.

The following code never completes - the `Console.WriteLine` is never reached. Putting breakpoints on the `return` statements reveals that one of them is reached, but the other never is.

``` cs
[Fact]
public async Task Test1()
{
    var barrier = new AsyncBarrier(2);

    var results = await Task.WhenAll(
        Task.Run(async () =>
        {
            await barrier.SignalAndWaitAsync();
            return 24;
        }),
        Task.Run(async () =>
        {
            await barrier.SignalAndWaitAsync();
            return 42;
        })
    );

    Console.WriteLine(string.Join(',', results));
}
```

**Comment by sakno** [comment]
@ascott18 , thanks for reporting bug. The commit with fix is already in `develop` branch. Could you please verify the fix? If everything fine I'll publish patched version on NuGet tomorrow.

**Comment by ascott18** [comment]
Thanks for the quick turnaround. If the test you added is passing then I'd say its good and fixed.

**Comment by sakno** [comment]
@ascott18 , release has been published on NuGet.
