### ISSUE TITLE
Example raft cluster consensus

### ISSUE THREAD

**Issue by LCastilloSymbiotic** [dotnet/dotNext#74]
Hi, 

I read your documentation and try to enter in this web link: https://github.com/sakno/dotNext/tree/develop/src/examples/RaftNode , but is show 404 error. I would like to know if you have some simple example project to use consensus for some data.

Greetings,

Luis

**Comment by sakno** [comment]
Hi @LCastilloSymbiotic , the link is broken because the project has moved to .NET Foundation. The correct link is  https://github.com/dotnet/dotNext/tree/develop/src/examples/RaftNode

**Comment by LCastilloSymbiotic** [comment]
Hi @sakno , I try to replicate your example, but when i try to import IClusterMemberLifetime to DotNext.Net.Cluster.Consensus.Raft; it's  show a not found exeception. Do you why?

**Comment by sakno** [comment]
Could you please provide a full stack trace?

**Comment by LCastilloSymbiotic** [comment]
I have this code, that's the same of your example:

```
using DotNext.Net.Cluster;
using DotNext.Net.Cluster.Consensus.Raft;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PaymentManagementServer.Services.Replication
{
    internal sealed class ClusterConfigurator : IClusterMemberLifetime
    {
        internal static void LeaderChanged(ICluster cluster, IClusterMember? leader)
        {
            Debug.Assert(cluster is IRaftCluster);
            var term = ((IRaftCluster)cluster).Term;
            var timeout = ((IRaftCluster)cluster).ElectionTimeout;
            Console.WriteLine(leader is null
                ? "Consensus cannot be reached"
                : $"New cluster leader is elected. Leader address is {leader.EndPoint}");
            Console.WriteLine($"Term of local cluster member is {term}. Election timeout {timeout}");
        }

        public void Initialize(IRaftCluster cluster, IDictionary<string, string> metadata)
        {
            cluster.LeaderChanged += LeaderChanged;
        }

        public void Shutdown(IRaftCluster cluster)
        {
            cluster.LeaderChanged -= LeaderChanged;
        }
    }
}
```

Generate this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'IClusterMemberLifetime' could not be found (are you missing a using directive or an assembly reference?)	PaymentManagementServer.Services	C:\Users\User\Documents\Symbiotic\Git\ToP-PMS\PaymentManagementServer\PaymentManagementServer.Services\Replication\ClusterConfigurator.cs	11	Active

**Comment by LCastilloSymbiotic** [comment]
Yes, I check, but i think the PakageReference is ok:

![image](https://user-images.githubusercontent.com/86098808/130813274-7c694b4b-4057-4d4d-9f6f-1a21890aa310.png)

**Comment by LCastilloSymbiotic** [comment]
In your example you import DotNext.Net.Cluster:


![image](https://user-images.githubusercontent.com/86098808/130815563-684d6a23-adab-40f0-900f-96ab0f946a07.png)

**Comment by sakno** [comment]
No, it has both imports: https://github.com/dotnet/dotNext/blob/master/src/examples/RaftNode/RaftNode.csproj#L25

**Comment by LCastilloSymbiotic** [comment]
Ok, that's work!!!

**Comment by LCastilloSymbiotic** [comment]
Hello,

I managed to execute the code of the example, and I read what you sent me, I have a doubt, the only thing that is synchronized (a consensus is reached) between the nodes is the Term that comes there or is it possible to customize the data to be replicated?

**Comment by sakno** [comment]
@LCastilloSymbiotic , of course, there is persistent Write-Ahead Log for that and you can implement state machine on top of it. Examine [this](https://dotnet.github.io/dotNext/features/cluster/wal.html) article for information. Also, the example has a replication process of monotonically increasing int64 counter.

**Comment by LCastilloSymbiotic** [comment]
Hi @sakno , your implementation of Int64 LogEntry, it is as follows:

```
    internal sealed class Int64LogEntry : BinaryTransferObject<long>, IRaftLogEntry
    {
        internal Int64LogEntry()
        {
            Timestamp = DateTimeOffset.UtcNow;
        }

        bool ILogEntry.IsSnapshot => false;

        public long Term { get; set; }

        public DateTimeOffset Timestamp { get; }
    }
}

```


I would like to do something like the following:

```
    public class ObjectLogEntry : BinaryTransferObject<Object>, IRaftLogEntry
    {
        internal ObjectLogEntry()
    {
        Timestamp = DateTimeOffset.UtcNow;
    }

    bool ILogEntry.IsSnapshot => false;

    public Object Term { get; set; }

    public DateTimeOffset Timestamp { get; }
}
```
But this does not work, since IRaftLogEntry (which a class in the library) uses a Long term, can I simply not use this interface or what other alternative is there?

**Comment by sakno** [comment]
No, Term is a part of Raft protocol and it should be int64. `BinaryTransferObject<Object>` is also invalid because generic parameter `T` must be of blittable type.

**Comment by sakno** [comment]
BTW, you don't need to implement `IRaftLogEntry` manually. You need to build state machine for interpreting log entries in the log. Take a look at [this](https://dotnet.github.io/dotNext/features/cluster/wal.html) article for more details about how persistent WAL is working.

**Comment by LCastilloSymbiotic** [comment]
Perfect, I'm going to read it!!!

**Comment by LCastilloSymbiotic** [comment]
To be sure if I understand, the structures to be replicated through consensus are serializable structures in JSON like the following, right?

```
struct SubtractCommand
{
	public int X { get; set; }
	public int Y { get; set; }
}
```

PD:Excuse me asking so many questions, I've been confused about this.

**Comment by sakno** [comment]
No, there is no restrictions about the actual binary format. JSON is just an option. For efficient I/O you need to implement `IFormatter<T>` for particular type according to documentation.

**Comment by LCastilloSymbiotic** [comment]
Ok yes, but see the example on the page you told me about:

![image](https://user-images.githubusercontent.com/86098808/131885264-ffb171f0-12cb-4c39-a639-5b942cf53865.png)

The "SubtractCommand" execute actions on the Value, I want value to be a custom data class, is there a problem with that?

**Comment by sakno** [comment]
No, but you need to implement serialization logic using `IFormatter<T>`.

**Comment by LCastilloSymbiotic** [comment]
ok, for example I have the following code:

![image](https://user-images.githubusercontent.com/86098808/131912278-c003cc2d-870a-4c01-835d-1cc68c2708ec.png)


I understand that when applying the operation "var entry = state.CreateJsonLogEntry (new SubtractCommand {X = 10, Y = 20});" This would be replicated in all nodes, right? I must use these commands to replicate the data and the consensus algorithm internally will take care of the consistency of the order of execution of this command in all the nodes, right?


Now in the hypothetical case that n nodes are alive and a node n + 1 connects to the network, this node (n + 1) would receive the last command which would allow it to be congruent with the rest of the nodes?

**Comment by sakno** [comment]
Yes, you can use built-in JSON support for convenience (but not for performance). Overriding `ApplyAsync` is necessary but not sufficient. Raft replicates the entire log entry starting from the last known position for the node. It means that if node had lost the connection with the leader at index 10 and then returned back to the cluster and leader has 20 more log entries then the leader will replicate all these 20 log entries. That's why here is a special log entry called _Snapshot_. Without the snapshot your log will grow indefinitely. Snapshot allows to squash commands in the log. For instance. the two commands `X = X + 10` and `X = X + 30` can be reduced to single command `X = X + 30`. That's why you need to override `CreateSnapshotBuilder` method as well to provide snapshot construction logic.

**Comment by LCastilloSymbiotic** [comment]
Ok, I will try to implement it, in my case it is necessary to apply it like this, since what I need to replicate is a complex object with various data.

**Comment by LCastilloSymbiotic** [comment]
Hi I've been trying to use your interpreter example, but it generates the following error:

![image](https://user-images.githubusercontent.com/86098808/132042611-36e7c717-e1cb-47fb-be81-0dea38a9a717.png)

Any idea why that may be?

**Comment by sakno** [comment]
Probably you're trying to register multiple command handlers with the same ID.

**Comment by LCastilloSymbiotic** [comment]
ok, i show yo the code:

```
 public class MyInterpreter : CommandInterpreter
	{
		public static SubtractCommand stateSubtract;
		public static NegateCommand stateNegate;

		[CommandHandler]
		public async ValueTask SubtractAsync(SubtractCommand command, CancellationToken token)
		{
			stateSubtract = command;

			Debug.WriteLine("I received Subtract {0}", command);
		}

		[CommandHandler(IsSnapshotHandler = true)]
		public async ValueTask HandleSnapshotSubtractAsync(SubtractCommand command, CancellationToken token)
		{
		}

		[CommandHandler]
		public async ValueTask NegateAsync(NegateCommand command, CancellationToken token)
		{
			stateNegate = command;

			Debug.WriteLine("I received Negate {0}", command);
		}

		[CommandHandler(IsSnapshotHandler = true)]
		public async ValueTask HandleSnapshotNegateAsync(NegateCommand command, CancellationToken token)
		{
		}
	}
```


```
sealed class CommandFormatter : IFormatter<SubtractCommand>, IFormatter<NegateCommand>
	{
		public static readonly CommandFormatter Instance = new CommandFormatter();

		private CommandFormatter()
		{
		}

		async ValueTask IFormatter<SubtractCommand>.SerializeAsync<TWriter>(SubtractCommand command, TWriter writer, CancellationToken token)
		{
			await writer.WriteInt32Async(command.X, true, token);
			await writer.WriteInt32Async(command.Y, true, token);
		}

		async ValueTask<SubtractCommand> IFormatter<SubtractCommand>.DeserializeAsync<TReader>(TReader reader, CancellationToken token)
		{
			return new SubtractCommand
			{
				X = await reader.ReadInt32Async(true, token),
				Y = await reader.ReadInt32Async(true, token)
			};
		}

		async ValueTask IFormatter<NegateCommand>.SerializeAsync<TWriter>(NegateCommand command, TWriter writer, CancellationToken token)
		{
			await writer.WriteInt32Async(command.X, true, token);
		}

		async ValueTask<NegateCommand> IFormatter<NegateCommand>.DeserializeAsync<TReader>(TReader reader, CancellationToken token)
		{
			return new NegateCommand
			{
				X = await reader.ReadInt32Async(true, token),
			};
		}
	}
```

```
	[CommandAttribute(1, Formatter = typeof(CommandFormatter), FormatterMember = nameof(CommandFormatter.Instance))]
	public struct NegateCommand
	{
		public int X { get; set; }
	}
```


```
	[CommandAttribute(0, Formatter = typeof(CommandFormatter), FormatterMember = nameof(CommandFormatter.Instance))]
	public struct SubtractCommand
	{
		public int X { get; set; }
		public int Y { get; set; }
	}
```

As I understand the only place where an id is placed is when creating the command, can you see that both id are different, do you see any error in that code?

**Comment by sakno** [comment]
Yes, you must have only one handler for each type of command. And of course you cannot have multiple handlers for the snapshot.

**Comment by LCastilloSymbiotic** [comment]
Ok it worked, I have another question, if I have the following structure:

```
    [CommandAttribute(2, Formatter = typeof(CommandFormatter), FormatterMember = nameof(CommandFormatter.Instance))]
    public struct DataCommand
    {
        public string StringData { get; set; }

        public int Test { get; set; }
    }
```

when I go to implement it in CommandFormatter it does not allow me to write strings:

![image](https://user-images.githubusercontent.com/86098808/132242198-34b9054c-f214-4881-a35a-0560d9d4ce8d.png)


Any solution for this problem?

**Comment by LCastilloSymbiotic** [comment]
I try to use JSON for alternative, in the PersistentState subclass, but show this error:

![image](https://user-images.githubusercontent.com/86098808/132243746-8f371fe1-e492-4804-bfae-261f38a5c494.png)

![image](https://user-images.githubusercontent.com/86098808/132243894-949d4b9f-e014-4300-95aa-e4b4b43fbaa0.png)

**Comment by sakno** [comment]
`IAsyncBinaryWriter` supports string serialization using the following method:
```csharp
ValueTask WriteAsync(ReadOnlyMemory<char> chars, EncodingContext context, LengthFormat? lengthFormat, CancellationToken token = default)
```

**Comment by sakno** [comment]
`CreateJsonLogEntry` is not supported for .NET Standard 2.1 target, only for .NET 5 target.

**Comment by LCastilloSymbiotic** [comment]
Do you have some example of `WriteAsync`?

**Comment by sakno** [comment]
You can find a lot of examples directly in tests: https://github.com/dotnet/dotNext/blob/master/src/DotNext.Tests/IO/AsyncBinaryReaderWriterTests.cs#L305

**Comment by LCastilloSymbiotic** [comment]
Do the samples work for .net core 3.1?


Bause your code is this:

```
        [Theory]
        [MemberData(nameof(GetDataForStringEncoding))]
        public static async Task WriteReadStringAsync(IAsyncBinaryReaderWriterSource source, Encoding encoding, LengthFormat? lengthFormat)
        {
            await using (source)
            {
                const string value = "Hello, world!&*(@&*(fghjwgfwffgw Привет, мир!";
                var writer = source.CreateWriter();
                await writer.WriteAsync(value.AsMemory(), encoding, lengthFormat);

                var reader = source.CreateReader();
                var result = await (lengthFormat is null ?
                    reader.ReadStringAsync(encoding.GetByteCount(value), encoding) :
                    reader.ReadStringAsync(lengthFormat.GetValueOrDefault(), encoding));
                Equal(value, result);
            }
        }
```

And my code show this error:

![image](https://user-images.githubusercontent.com/86098808/132249139-e79888ac-9c73-40a5-8d95-7f6b576400e3.png)

The other problem I have is the constant, that AsMemory () can be used with string variables?

**Comment by sakno** [comment]
In C#, there is no way to restrict the method to be called only on `const` value.

**Comment by LCastilloSymbiotic** [comment]
In your example, you use this to read:

```
 var result = await (lengthFormat is null ?
                    reader.ReadStringAsync(encoding.GetByteCount(value), encoding) :
                    reader.ReadStringAsync(lengthFormat.GetValueOrDefault(), encoding));
```
but in the library (net.core 3.1) the overload for ReadStringAsync are there:

![image](https://user-images.githubusercontent.com/86098808/132250989-084493d8-473c-47e0-89c2-90145736e69c.png)

What i need to send in DecodingContext context? Can i send null?

![image](https://user-images.githubusercontent.com/86098808/132251151-12391ea1-537d-420f-a309-61aa128455e1.png)

**Comment by LCastilloSymbiotic** [comment]
Hi, I got the string send to work, instead of putting null, I put default and it worked.

**Comment by LCastilloSymbiotic** [comment]
I have a question about the operation of the cluster, doing tests I notice that the commands "sent" by the cluster are replicated, but if they are sent by the slave this is not done, how can I enable or make the commands to be issued by the slave as well replicate?

**Comment by LCastilloSymbiotic** [comment]
In you example, leader node is the only node can share or replicate information:

![image](https://user-images.githubusercontent.com/86098808/132375280-ef2c209c-b9db-4f1c-b8e1-30233ea502b6.png)

A normal node can replicate?

**Comment by LCastilloSymbiotic** [comment]
Or is there a way for a slave node to send a command to the master?

**Comment by sakno** [comment]
According to Raft protocol only the leader node is responsible for replication. Otherwise, it's a violation of data consistency and linearizability. I recommend you to read basics about Raft [here](https://raft.github.io/raft.pdf).

**Comment by LCastilloSymbiotic** [comment]
Hello, thank you very much for your collaboration throughout these days, I have already managed to implement the library 100%, I will proceed to close the topic. Thank you!!!
