### ISSUE TITLE
IMemberDiscoveryService 

### ISSUE THREAD

**Issue by LCastilloSymbiotic** [dotnet/dotNext#76]
Hi, 

Do you have a example to use `IMemberDiscoveryService?` I would like to add members dynamically in the cluster...

Best regards,

Luis

**Comment by LCastilloSymbiotic** [comment]
Hi In 3.x, Is it possible to add a node manually? 

I am trying something like this:

```
private readonly IRaftCluster _cluster;

IPEndPoint checkIP = new IPEndPoint(IPAddress.Loopback), 3262);
_cluster.Members.Aggregate(checkIP);
```
But I get an error for the type as it requests an `IClusterMember`

**Comment by sakno** [comment]
It does.

**Comment by sakno** [comment]
.NET JSON configuration uses JSON arrays instead of indexing array elements directly:
```json
{
  "members": ["https://192.168.31.144:3262"]
}
```

**Comment by sakno** [comment]
Closing the issue due to inactivity.
