### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by mbasij1** [dotnet/dotNext#78]
For best performance, we use TcpConfiguration and create a simple k/v Store, that uses a simple dictionary. And not a configuration snapshot in PersistentState. we found that the optimistic way to create log entries is using fixed struct size like example. but I get 136ms avg latency that is very high for me.
SqlServer instance give me 40ms avg latency for the same job! and we need 1-3ms avg latency.
I wanna know we could reach 3ms with this library or should use other libraries?

**Comment by sakno** [comment]
Release 4.2.0 includes many optimizations aimed to improve response time.

Replication of a single log entry of size 8 Kb takes ~10,7 ms for a single entry with the following settings
* 1 GB Ethernet interface
* `MemoryBasedStateMachine.Options.EvictionPolicy = LogEntryCacheEvictionPolicy.OnSnapshot`
* `PersistentState.Options.WriteMode = WriteMode.AutoFlush`
* Compaction mode is _Incremental_

Replication of multiple log entries of size 8 Kb takes ~6,28 ms for a single entry with the settings mentioned above.

Disk write requires about 6 ms so I don't see any way to reduce it up to 1 ms.
