### ISSUE TITLE
RaftCluster odd behavior when implementing your own IPersistentState

### ISSUE THREAD

**Issue by Arkensor** [dotnet/dotNext#99]
Hey :)

I have run into the requirement to make my own IPersistentState implementation and that has worked out alright so far until I wanted to add snapshot / log compaction support.

I have spent the whole day debugging the source code to trace down what is happening and I feel like I am either overlooking something or there is a logic flaw.

Let's start of wit the experiment setup:
- I am using the latest develop source (but this happend on the beta nuget-packages as well)
- I start a cluster with one member who becomes leader and is ready to accept work
- During the `IPersistentState` init or at any point before someone else joins a snapshot entry is put into the log. e.g the cluster ran for a while and had entries for index 1-500 (0 is never used). The snapshot combines 1-500 into a snapshot log entry at index 500 - essentially taking the place of the last log entry it represents. All log entries with an index < than 500 are dropped.
- I start a follower to ask the leader to add him through `AddMemberAsync`
- The follower is being added and replication runs
- The follower is successfully replicated and his presence is suggested as new member configuration
... so far so good, but here the fun begins. 

I based my implementation on what I saw in `ConsensusOnlyState` - but what I saw in the `PersistentState` seemed to be the same in what is to come.

From what I understand and read in the source the process intends for the catch-up rounds to take place and then the member is added. During this catch-up the is a variable `member.NextIndex` that represents the next log index to be sent. Eventually this number is larger than what is actually in the leader log, so he starts to send nothing (heartbeats). 
What I would have *expected* is for the member to be passed into the leader state and continue his existence with the known `member.NextIndex`. But I checked the vanilla implementations and this information is forgotten. **Why?**
As very first step after being part of the normal leader state the member will start at `member.NextIndex == 0` and the leader must read his log, to fetch all entries from `0 - auditTrail.LastUncommittedEntryIndex` and send them over to the **already** caught-up follower. I have not seen anything in this regard that my `IPersistentState` could have affected.

Now that is the first problem / question. Why does he do the catch-up to forget where the member was at and have to find out again.

By itself, this would not be much of an issue - just waste of performance (if there is no algorithmic necessity - which I don't know).
What **is a big problem** for me is getting snapshots to work with this. I do not understand why they work for the existing state machines but not for mine. The leader will refetch the entire log ... and this log contains my snapshot. By their nature the snapshots of course always come first in the log. So in my setup the snapshot that is present on the leader at index 500 (representing index 1-500) sits there together with a log entry at index 501 (the leader who has elected himself in the empty cluster) and the new member config for the joining follower at 502. 
The `ILogEntryConsumer.ReadAsync<TEntryImpl, TList>` function that is doing the reading on my log wants a parameter `long? snapshotIndex`. I understood this parameter as "if your first entry in the range to be read is represented by a snapshot, return the snapshot index here" - and this seems to be backed up by the source that checks for `snapshotIndex.HasValue` and then only even cares about `entries[0` (LeaderState.Replication.cs `ReadAsync<TEntry, TList>`)

So here is the problem. My log contains [Snapshot(500), EmptyLogEntry(501), EmptyLogEntry(502)] and since the leader forgot where the follower was at, he asks for `0-end`. This list contains / starts with a snapshot so I return the snapshot and put 500 as `snapshotIndex` parameter. Now the caller logic thinks "oh I need to call `member.InstallSnapshotAsync(term, entries[0], currentIndex, token)` - which is ok - but this will 100% of the time fail ... because the follower already has this snapshot installed. He got all the data in the catch-up rounds. So this bit of code running on the follower rejects every attempt from the leader to sync this snapshot:
RaftCluster.cs Line 396ff
```cs
    protected async Task<Result<bool>> InstallSnapshotAsync<TSnapshot>(ClusterMemberId sender, long senderTerm, TSnapshot snapshot, long snapshotIndex, CancellationToken token)
        where TSnapshot : notnull, IRaftLogEntry
    {
        using var tokenSource = token.LinkTo(LifecycleToken);
        using var transitionLock = await transitionSync.AcquireAsync(token).ConfigureAwait(false);
        var currentTerm = auditTrail.Term;

        //snapshotIndex > auditTrail.LastCommittedEntryIndex WILL NEVER BE TRUE!!!!!!!!
        if (snapshot.IsSnapshot && senderTerm >= currentTerm && snapshotIndex > auditTrail.LastCommittedEntryIndex)
        {
            Timestamp.Refresh(ref lastUpdated);
            await StepDown(senderTerm).ConfigureAwait(false);
            Leader = TryGetMember(sender);
            await auditTrail.AppendAsync(snapshot, snapshotIndex, token).ConfigureAwait(false);
            return new(currentTerm, true);
        }

        return new(currentTerm, false);
    }
```
So a snapshot can not be installed, even though it already was in the past, but if I can't install the snapshot the rest of the data will not sync and the `member.NextIndex` remains `0` for ever. If I do not mark my snapshot as such in the  `ILogEntryConsumer.ReadAsync<TEntryImpl, TList>` it arrives as regular log entry and my logic has no idea it was supposed to be a snapshot and applies it again - destroying my local data - because this snapshot was technically already installed once. 
If I don't return the snapshot index, its treated as normal entry and my log has no idea that snapshot exists. If I declare it a proper snapshot, it can never get in sync after the catch-up because that already installed the snapshot.

So my question is ... is this a bug? I am too stupid to implement `IPersistentState` correclty? Did I miss some docs or missunderstood Raft? I mean this must be working for the file based state machines, but I could not figure out what they do differently.

In my code I accept all Append overloads into a single handler and it does this check
```cs
if (entry.IsSnapshot)
{
    //A snapshot must be received first in order, and it wipes any state that came before it.
    _highestLogTerm.VolatileWrite(entry.Term);
    _highestLogIndex.VolatileWrite(startIndex);
    _commitedLogIndex.VolatileWrite(startIndex);
    _commitEvent.Set(true);
}
else
{
    //Increment index for latest log entry appended
    _highestLogIndex.VolatileWrite(startIndex);
}
```
I saw this in the ConsensusOnlyState. I think it should be technically correct to update the log index, commit index, and term to what is presented by a snapshot supplied to `AppendAsync` since those must have been committed already in the past.

My idea would be for the leader state to not forget the `member.NextIndex` as then he would not attempt to sync the snapshot or anything else again. If that can not be changed then the `InstallSnapshotAsync` logic should maybe check for `auditTrail.LastCommittedEntryIndex >= snapshotIndex` and return success? ... but I guess that might destory something because this is also used to override outdated data on a partitioned follower that connects again? 

I am not sure ... It would be very very nice to get some feedback on what is going on / what I am doing wrong. I have been sitting on this for the last 10 hours straight and can't figure it out. 

Sorry for the wall of text (yet again) 🍪 

Thanks!

**Comment by sakno** [comment]
@Arkensor , thanks for such a detailed investigation. In short, this behavior can be considered as a bug. We need to assume that newly added member is in sync with the leader (or at least close to that state). In this case, `NextIndex` must be set to `LastUncommittedEntryIndex + 1` as it done in catch-up procedure. The leader later can easily detect that this assumption is wrong and decrements `NextIndex` down to the correct index when the member will respond with success.

The fix is trivial and requires just one line of code.

**Comment by Arkensor** [comment]
@sakno thank you for quickly looking into this. I have applied your edit from [36bff69](https://github.com/dotnet/dotNext/commit/36bff69cbac454018461553a3052d3719411295b) to my local debug code and now the process behaves as expected.

I'd be grateful if you could push this fix as updated beta nuget package soon, so I can switch back to my normal project setup without having to build all the source as well :)

**Comment by sakno** [comment]
@Arkensor , I'm expecting to release 4.2.0 today or tomorrow. Anyway, if the release will be delayed for some reason I'll make a new beta release.
